// ============================================
// AUTOMATION ENGINE v2 - Document Generation Mode
// Discovers opportunities and generates documents
// User applies manually with generated docs
// ============================================

import { discoveryService, ScraperType, ALL_SCRAPERS } from './discovery-service';
import { getAllOpportunities, getEligibleOpportunities, Opportunity, getStats } from './opportunity-store';
import { generateAndStoreDocuments, getAllDocuments, getDocumentStats } from './document-store';
import { browserManager } from './browser';

export interface AutomationConfig {
    // Discovery settings - NO LIMITS
    discoveryIntervalMs: number; // How often to scan (default: 1 hour)
    enabledScrapers: ScraperType[];
    minMatchScore: number; // Minimum score to generate docs (default: 60)

    // Document generation - UNLIMITED
    autoGenerateDocs: boolean; // Auto-generate docs after discovery

    // Mode settings
    autoStart: boolean;
}

export interface AutomationStatus {
    running: boolean;
    lastDiscoveryScan: Date | null;
    lastDocumentGeneration: Date | null;
    totalDiscovered: number;
    totalDocumentsGenerated: number;
    currentActivity: string;
    errors: string[];
}

const DEFAULT_CONFIG: AutomationConfig = {
    discoveryIntervalMs: 60 * 60 * 1000, // 1 hour - more frequent scanning
    enabledScrapers: ALL_SCRAPERS, // ALL scrapers enabled
    minMatchScore: 60, // Lower threshold - more opportunities
    autoGenerateDocs: true,
    autoStart: true,
};

/**
 * AutomationEngine v2 - Document Generation Focus
 * 
 * Flow:
 * 1. Discover opportunities from ALL sources (no limit)
 * 2. Match against profile
 * 3. Generate tailored documents (CV, essay, cover letter)
 * 4. Store documents for user to review and apply manually
 */
export class AutomationEngine {
    private static instance: AutomationEngine;
    private config: AutomationConfig;
    private status: AutomationStatus;

    private discoveryTimer: NodeJS.Timeout | null = null;
    private documentTimer: NodeJS.Timeout | null = null;
    private isProcessing = false;

    private constructor() {
        this.config = { ...DEFAULT_CONFIG };
        this.status = {
            running: false,
            lastDiscoveryScan: null,
            lastDocumentGeneration: null,
            totalDiscovered: 0,
            totalDocumentsGenerated: 0,
            currentActivity: 'Idle',
            errors: [],
        };
    }

    static getInstance(): AutomationEngine {
        if (!AutomationEngine.instance) {
            AutomationEngine.instance = new AutomationEngine();
        }
        return AutomationEngine.instance;
    }

    // ============================================
    // PUBLIC API
    // ============================================

    async start(): Promise<void> {
        if (this.status.running) {
            this.log('Engine already running');
            return;
        }

        this.log('🚀 Starting Automation Engine (Document Generation Mode)...');
        this.status.running = true;
        this.status.currentActivity = 'Starting up';

        await browserManager.initialize();

        // Run initial discovery
        this.runDiscoveryAndGenerate();

        // Schedule periodic discovery - NO LIMIT
        this.discoveryTimer = setInterval(
            () => this.runDiscoveryAndGenerate(),
            this.config.discoveryIntervalMs
        );

        this.log('✅ Automation Engine started');
        this.log(`📡 Scanning ${this.config.enabledScrapers.length} sources every ${this.config.discoveryIntervalMs / 1000 / 60} minutes`);
        this.log(`📝 Min match score for doc generation: ${this.config.minMatchScore}`);
        this.log(`📄 Mode: DOCUMENT GENERATION (no auto-apply)`);
    }

    async stop(): Promise<void> {
        if (!this.status.running) {
            this.log('Engine not running');
            return;
        }

        this.log('🛑 Stopping Automation Engine...');
        this.status.running = false;
        this.status.currentActivity = 'Stopping';

        if (this.discoveryTimer) {
            clearInterval(this.discoveryTimer);
            this.discoveryTimer = null;
        }
        if (this.documentTimer) {
            clearTimeout(this.documentTimer);
            this.documentTimer = null;
        }

        await browserManager.close();
        this.status.currentActivity = 'Stopped';
        this.log('✅ Automation Engine stopped');
    }

    getStatus(): AutomationStatus {
        const stats = getStats();
        const docStats = getDocumentStats();
        return {
            ...this.status,
            totalDiscovered: stats.total,
            totalDocumentsGenerated: docStats.totalOpportunities,
        };
    }

    updateConfig(updates: Partial<AutomationConfig>): void {
        this.config = { ...this.config, ...updates };
        this.log(`⚙️ Config updated: ${JSON.stringify(updates)}`);

        if (updates.discoveryIntervalMs && this.status.running) {
            if (this.discoveryTimer) {
                clearInterval(this.discoveryTimer);
            }
            this.discoveryTimer = setInterval(
                () => this.runDiscoveryAndGenerate(),
                this.config.discoveryIntervalMs
            );
        }
    }

    getConfig(): AutomationConfig {
        return { ...this.config };
    }

    async triggerDiscovery(): Promise<void> {
        await this.runDiscoveryAndGenerate();
    }

    getLogs(): string[] {
        return browserManager.getState().logs;
    }

    // ============================================
    // INTERNAL - Discovery + Document Generation
    // ============================================

    private async runDiscoveryAndGenerate(): Promise<void> {
        if (!this.status.running || this.isProcessing) return;

        this.isProcessing = true;
        this.status.currentActivity = 'Discovering opportunities...';
        this.log('🔍 Starting UNLIMITED discovery scan...');

        try {
            // STEP 1: Discover from ALL sources
            const results = await discoveryService.scan(this.config.enabledScrapers);
            const totalFound = results.reduce((sum, r) => sum + r.found, 0);
            this.status.lastDiscoveryScan = new Date();

            this.log(`✅ Discovery complete! Found ${totalFound} total opportunities`);
            results.forEach(r => {
                if (r.success && r.found > 0) {
                    this.log(`   📌 ${r.scraper}: ${r.found} found`);
                }
            });

            // STEP 2: Generate documents for eligible opportunities
            if (this.config.autoGenerateDocs) {
                await this.generateDocumentsForAll();
            }

        } catch (error) {
            const msg = error instanceof Error ? error.message : String(error);
            this.log(`❌ Discovery error: ${msg}`);
            this.status.errors.push(msg);
        } finally {
            this.isProcessing = false;
            this.status.currentActivity = 'Waiting for next scan...';
        }
    }

    private async generateDocumentsForAll(): Promise<void> {
        this.status.currentActivity = 'Generating tailored documents...';
        this.log('📄 Generating documents for eligible opportunities...');

        const eligible = getEligibleOpportunities(this.config.minMatchScore);

        // Import the builder dynamically or at top-level
        const { buildFullProfile } = await import('./user-profile');
        const realProfile = buildFullProfile();

        let generated = 0;

        for (const opp of eligible) {
            try {
                // Pass the real profile
                generateAndStoreDocuments(opp, realProfile);
                generated++;
                this.log(`   ✓ ${opp.title} @ ${opp.organization}`);

                // Small delay to not overwhelm
                await new Promise(r => setTimeout(r, 100));
            } catch (error) {
                const msg = error instanceof Error ? error.message : String(error);
                this.log(`   ✗ Error generating for ${opp.title}: ${msg}`);
            }
        }

        this.status.lastDocumentGeneration = new Date();
        const stats = getDocumentStats();
        this.log(`✅ Documents ready: ${stats.totalCVs} CVs, ${stats.totalEssays} essays, ${stats.totalCoverLetters} cover letters`);
        this.log(`📊 Total: ${stats.jobDocuments} jobs, ${stats.scholarshipDocuments} scholarships`);
    }

    private log(message: string): void {
        browserManager.log(`[Engine] ${message}`);
    }
}

export const automationEngine = AutomationEngine.getInstance();
